sudo: required
services:
  - docker

before_install:
  - docker build -t bassemghoniem/dockerized-react -f Dockerfile.dev .

script:
  - docker run bassemghoniem/dockerized-react npm run test -- --coverage