sudo: required
services:
  - docker

before_install:
  - docker build -t bassemghoniem/dockerized-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bassemghoniem/dockerized-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockerized-react"
  env: "DockerizedReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-471358053311"
  bucker_path: "dockerized-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
